name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Setup Java JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build and Test
      run: mvn clean package verify surefire-report:report

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: show-management.jar
        path: target/show-management.jar

    - name: Upload Surefire Report
      uses: actions/upload-artifact@v3.1.3
      with:
        name: surefire-report
        path: target/site/*
